#!/usr/bin/env python
###############################################################################
#
#  Copyright (C) 2014  Thammi
# 
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
# 
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
###############################################################################
#
#  This script checks whether a STUN server is up
#
#  Dependencies:
#
#   pip install pystun
#
#  Usage:
#
#   ./stuncheck $STUN_ADDRESS
#
###############################################################################

import stun
import sys

# parse url

host_parts = sys.argv[1].split(':')

if host_parts[0] == 'stun':
    del host_parts[0]

opts = {}

if len(host_parts) == 1:
    opts['stun_host'] = host_parts[0]
elif len(host_parts) == 2:
    opts['stun_host'] = host_parts[0]
    opts['stun_port'] = int(host_parts[1])
else:
    print("Unable to parse STUN address")
    sys.exit(1)

# do stun stuff

nat_type, ip, port = stun.get_ip_info(**opts)

# output

if nat_type == 'Blocked':
	print("Unable to connect to STUN server")
	sys.exit(2)
else:
	print("Detected ip %s behind %s" % (ip, nat_type))
	sys.exit(0)

